services:
  estacionafacil.api:
    container_name: estaciona.facil.api
    image: ${DOCKER_REGISTRY-}estacionafacilapi
    build:
      context: .
      dockerfile: src/EstacionaFacil.Api/Dockerfile
    depends_on:
      - estaciona.facil.db
    networks:
      - estacionamento-network

  estaciona.facil.db:
    container_name: estaciona.facil.db
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=EstacionaFacilDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - estacionamento-network

  pgadmin:
    container_name: estaciona.facil.pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: marcosfas.dev@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - estaciona.facil.db
    networks:
      - estacionamento-network
 
volumes:
  db_data:
    driver: local

networks:
  estacionamento-network:
    driver: bridge
